### ISSUE TITLE
Recommendations for input vcf

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/HiPhase#16]
Hi @holtjma,

Would you be able to share the DeepVariant parameters and filtering steps you use at PacBio before applying hiphase? I'd like to be as consistent as I can with your process! Sorry if this is documented and I missed it. 

Cheers,
Mitchell

**Comment by holtjma** [comment]
Hey Mitchell,

For testing, we've basically been using the [pb-human-wgs-workflow-snakemake](https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake).  The specific DeepVariant part can be found here: https://github.com/PacificBiosciences/pb-human-wgs-workflow-snakemake/blob/main/rules/sample_deepvariant.smk 

Other components, like parameters for pbmm2, can also be found in that repo.

Matt

**Comment by holtjma** [comment]
I should mention that if you want a simple one-liner based on Docker, then you can use the built-in wrapper command like here:

https://github.com/google/deepvariant/blob/r1.5/docs/deepvariant-pacbio-model-case-study.md 

My understanding is that these are equivalent.

**Comment by mrvollger** [comment]
Awesome! looks like very minimal filtering :)! 

Thanks for the quick response.
