### ISSUE TITLE
A question about HP tag

### ISSUE THREAD

**Issue by oceancongliu** [PacificBiosciences/HiPhase#18]
Hi, good news to hear you developed a useful tool to analyse HIFI data.
I used this tool to analysis my whole genome sequencing data based seq IIe platform. Subreads of one child and his parents NGS datas were got, I want to phase methylation locus and  to compare the difference between the two haplotypes.

From user guide instruction,  HiPhase follows the same haplotagging convention as WhatsHap,and each mapping is tagged with both a phase set ID (PS) and a haplotype ID (HP). So, what is the relationship of 1 and 2 to their parents? the  HP tag  "1"  represent his paternal resource or the  HP tag  "2"  represent his maternal resource?

The second quenstion: Within a single phase block, all mappings with the same read name will have the same HP tag. Mappings of the same read to different phase blocks (e.g. to different chromosomes) are not guaranteed to have matching HP tags. Can you explain this sentence clearly? Is it possible that HP tag "1" or HP tag "2" has different meanings on different chromosomes?

Looking forward to your reply.
THANKS.

**Comment by holtjma** [comment]
Hello,

> From user guide instruction, HiPhase follows the same haplotagging convention as WhatsHap,and each mapping is tagged with both a phase set ID (PS) and a haplotype ID (HP). So, what is the relationship of 1 and 2 to their parents? the HP tag "1" represent his paternal resource or the HP tag "2" represent his maternal resource?

HiPhase is a read-backed phaser only right now, so the short answer is that there is no relationship between the HP tag output and the maternal/paternal origin.  A separate step would need to ingest the phased VCF as well as the pedigree and assign each haplotype to maternal/paternal origin.  Currently, HiPhase does not do that.

>The second quenstion: Within a single phase block, all mappings with the same read name will have the same HP tag. Mappings of the same read to different phase blocks (e.g. to different chromosomes) are not guaranteed to have matching HP tags. Can you explain this sentence clearly? Is it possible that HP tag "1" or HP tag "2" has different meanings on different chromosomes?

Yea, so HP "1" or "2" are just arbitrary labels representing the two haplotypes within a single phase block.  In HiPhase, this corresponds to the "first" and "second" set of alleles.  The meaning of "1" and "2" is only meaningful _within a phase block_.  Once you step outside of the phase block, there is a 50% chance that the phase blocks "flip" relative to each other.  This is because there were no spanning reads to connect two consecutive heterozygous variants.  To my knowledge, this definition of HP "1" or "2" is fairly standard for read-backed phasing tools.

An example, if you had 3 variants with the following GT fields:
```
0|1
0|1
1|0
```

Then, we would expect HP:1 and HP:2 to contain variants correspond to alleles:
```
HP:1 001
HP:2 110
```

Let me know if you have follow-up questions or clarifications!

Matt

**Comment by oceancongliu** [comment]
Hi, Matt, 
Thank you for your reply, i have read you answer patiently and I have got the answer I need.

Another question: I have compared this tool with WhatShap. From the instruction of  WhatShap, In the resulting VCF file (phased.vcf), haplotype alleles of a child were given as paternal | maternal, does this mean  that  paternal | maternal only exist a single  phase set,same with Hiphase?

Thanks,
Cong.

**Comment by holtjma** [comment]
My understanding is that the ordered phasing like that only applies if you specifically provide a pedigree file, like so: 
https://whatshap.readthedocs.io/en/latest/guide.html#phasing-pedigrees.  I have not tested this mode of WhatsHap, so I can’t comment on the accuracy or compute costs.

If you do not provide a pedigree file, my understanding is the behavior is the same as HiPhase (i.e. there is no association between 1/2 and maternal/paternal).

For your use case, are you wanting to do both read-backed and trio phasing at the same time?

**Comment by oceancongliu** [comment]
Hi, Matt,
As you mentioned,  I tested the Pedigree Phasing model of  WhatsHap, offering  pedigree file and trio SNV infimations following the instruction (https://link.springer.com/protocol/10.1007/978-1-0716-2819-5_8#Abs1). The haplotypes in the resulting variant file are reported as paternal|maternal in the GT tag. That is, the first allele is the one inherited from the father and the second one is the allele inherited from the mother.

My main goal was to trio phasing the reads of the child, get the methylation information from the paternal and maternal haplotype, try to look for differences. I need to know the association between HP:i:1/2  and maternal/paternal. 

If whatshap works smoothly, Can this tool solve my problem? or, do you have any better advice?

THANKS

**Comment by holtjma** [comment]
I can't vouch for the accuracy of the pedigree-based phasing of WhatsHap (I've never benchmarked it).  However, if I needed that analysis _today_, it's what I would start with given the current tooling.  One possible suggestion is that you could provide the HiPhase results to WhatsHap through this mechanism: https://whatshap.readthedocs.io/en/latest/guide.html#vcfs-as-reads.  Again, I have not tested this, so I can't vouch for the accuracy of the result.

Pedigree phasing is a potential improvement we may make to HiPhase at some point, but I don't know if or when that will happen.

**Comment by oceancongliu** [comment]
Thanks for your generous help and suggestion, i will try to combin with HiPhase and WhatsHap. 
I think that a progressive algorithm will help a lot.
I hope HiPhase will be better in the future.

THANKS.
