### ISSUE TITLE
Feature request: haplotag in phased VCF files

### ISSUE THREAD

**Issue by andyjslee** [PacificBiosciences/HiPhase#25]
Thank you for developing such a useful tool! Would it be possible to include the haplotag information (stored in the `--haplotag-file` file) in the phased VCF files? HiPhase currently only outputs `PS` (phase set identifier) in the phased VCF files.

**Comment by holtjma** [comment]
Hi @andyjslee,

If you're referring to the `haplotag` column, that is implicitly encoded in the VCF file.  For example, if `GT=1|0`, it indicates that the ALT allele is in haplotype 1 and the REF allele is in haplotype 2.  Are you referring to that or something else?

Matt

**Comment by andyjslee** [comment]
Thank you for your quick response. You are right. I'll close this issue/feature request. Thank you!
