### ISSUE TITLE
gVCF + VCF processing 

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/HiPhase#40]
Hi @holtjma!

We have some samples where we would like to phase a gVCF as well as a VCF with basically the same information in them, and it brought up a couple of questions.

1) Can you safely process a gVCF and a VCF in the same hiphase run even though for variant sites the vcfs will have totally redundant information?

2) If we first run the VCF and the gVCF in two different hiphase runs can we expect the H1/H2 assignments to be consistent between the two files?

Thanks in advance!
Mitchell

CCing @adrisede to keep her in the loop

**Comment by holtjma** [comment]
Hmm, I have not done this, but here's what I think will happen:

1. Assuming these are truly representing the same variants AND that every additional entry in the gVCF is a 0/0 call, I _think_ it might work.  There are similar situations with overlapping calls in DeepVariant / pbsv, and HiPhase will correctly handle it when those calls are identical.  However, I've never tried it at the scale you're describing, so it's possible there is some strange edge case.
2. With the same assumptions above, I would _expect_ to get the same H1/H2 assignments.  Again, I have not verified that.

If the assumptions I stated above are true, is there a reason you can't just run the gVCF file and then filter it down to a VCF?  That seems less likely to hit an error or odd edge case (both in HiPhase and potentially elsewhere), and would likely have less compute requirements than trying to run redundant info through HiPhase.

Matt

**Comment by mrvollger** [comment]
The gVCF and then filter is almost certainly the best idea, but I wanted to process the gVCF and VCF output of deepvariant in the exact same way, and I haven't had success recreating the deepvariant vcf by filtering the gVCF with simple ideas at least.

e.g.
```
bcftools view -i 'GT[*]="alt"' deep.gvcf.gz | wc -l
bcftools view -i deep.vcf.gz | wc -l
```
give me pretty different numbers because deepvariant includes some but not all "RefCalls" and some other things.

If you know the filter to apply here, that would be great! but if not you can close I think, since this may be more about how deepvariant subsets during gvcf -> vcf.

**Comment by mrvollger** [comment]
I figured out the filtering, I was getting messed up by the gVCF (left) including `<*>` in every(?) position compared to the vcf (right).
<img width="1109" alt="image" src="https://github.com/PacificBiosciences/HiPhase/assets/6935283/c8b8ef24-1a40-457e-ada0-9343bf265031">
So I just need to figure out what that is and potentially drop it. It doesn't seem like it should actually mean potential upstream deletion as implied by the spec.

**Comment by holtjma** [comment]
@mrvollger, I asked our group, @williamrowell thinks this will handle most cases:

```
bcftools view \
    --exclude-uncalled --min-ac 1 $GVCF \
    | bcftools convert --gvcf2vcf --fasta-ref $REF - \
    | bcftools view --trim-alt-alleles
```

We didn't do a deep test on this command, but it might help get you closer!

**Comment by mrvollger** [comment]
Thanks @holtjma and @williamrowell!

I came up with this command, and on the two files I tested, the output is identical save a program tag
```
        bcftools view \
            --threads {threads} \
            -e'FILTER="."' -AA \
            --write-index -o {output.vcf} \
            {input.gvcf}
```
Do you see any obvious issues with this vs what you have done?

**Comment by williamrowell** [comment]
Seems reasonable, but haven't dug into it too much.
