### ISSUE TITLE
Question on tagging of supplemental alignments

### ISSUE THREAD

**Issue by mrvollger** [PacificBiosciences/HiPhase#5]
Hi Matt,

Thanks again for the great tool. I am wondering, how are supplemental reads tagged? are they treated as their own reads or do they "inherit" the HP and PS of the primary alignment?

Thanks!
Mitchell

**Comment by holtjma** [comment]
Mitchell,

Within a given phase block, each read mapping gets converted into a set of alleles based on the provided variants.  Afterwards, all mappings with the same read name are **collapsed** into a single read observation.  This means that within a block, all primary and supplementary mappings for a read are effectively fused together into a single unit, and will receive the same PS and HP tags throughout that phase block.

Note that this is just within a block, if the mappings are in different blocks (i.e. too far apart or different contigs), then they can get different PS and HP tags.  Does that clarify it?

Matt

**Comment by mrvollger** [comment]
Perfect. Thanks!
