### ISSUE TITLE
Output Phase Block GTF 

### ISSUE THREAD

**Issue by minw2828** [PacificBiosciences/HiPhase#50]
Hello HiPhase team, 

Thank you for developing the tool. :)

I am wondering if it is possible to output the phase blocks in the GTF format as [`WhatsHap`](https://whatshap.readthedocs.io/en/latest/guide.html#gtf-with-haplotype-blocks) does.  
As you can see in the [`WhatsHap` manual](https://whatshap.readthedocs.io/en/latest/guide.html#gtf-with-haplotype-blocks), the GTF file can be loaded into IGV for visualisation. The GTF file also makes it easy for downstream programmatic analyses. 

The `WhatsHap` command to output the GTF file was designed to take 1 small variant VCF file as input. While `HiPhase` can take both the small variants and the structural variants into account to produce a `hiphase.bam` file, I cannot provide the small variant VCF and the structural variant VCF to `WhatsHap` to generate a GTF file that corresponds to the `hiphase.bam` file.

Currently, `HiPhase` provides a [`--blocks-file` option](https://github.com/PacificBiosciences/HiPhase/blob/main/docs/user_guide.md#output-files). However, this generates a CSV/TSV file which cannot be utilised by IGV properly. As shown in the screenshot below, the TSV file was shown as a side bar in IGV, which is not intuitive to the user where the phase block starts and ends.
![Screenshot 2024-10-10 at 1 37 51 PM](https://github.com/user-attachments/assets/8602ca77-65a5-4d7c-a053-a236a9b94190)

Hence, it would be good if your team could enable an option to produce a phase block GTF file that corresponds to the `hiphase.bam` file, taking both the small variants and structural variants into account. 

Apologise in advance if the feature of generating a phase_block.gtf has already been implemented. If this is the case, please let me know how to output the GTF file.  

Many thanks,
Min

**Comment by minw2828** [comment]
Sorry about this. I realise how to resolve this. Thank you!

**Comment by holtjma** [comment]
Hi @minw2828,

As you may have realized, with some file manipulation you can turn the blocks file into a BED file which you can load into IGV with relative ease.  We are unlikely to generate a GTF file in our outputs, so I would recommend that or a similar work-around.

Matt

**Comment by minw2828** [comment]
Hi Matt,

Yes, that's exactly what I did. Thank you! 

Sorry about using this as my thinking pad. I don't know how to delete my issue after I regretly posted it. 

Thank again! 
Min
