### ISSUE TITLE
How to Generate Haplotype 1 and 2 FASTA Files Using Phased VCF from HiPhase

### ISSUE THREAD

**Issue by ClarenceHsiang** [PacificBiosciences/HiPhase#51]
Dear HiPhase :
I attempted to use bcftools to generate haplotype sequences, but the process was unsuccessful. Are there alternative solutions available? Below is the code I used:
bcftools consensus -f reference_genome.fasta -H 1 output_phased_variants.vcf.gz > haplotype1.fasta
bcftools consensus -f reference_genome.fasta -H 2 output_phased_variants.vcf.gz > haplotype2.fasta

Sincerely,

Clarence

**Comment by ClarenceHsiang** [comment]
Thank you very much for your response. The relevant error messages are as follows:

[Clarence]$ /data/share/tools/bcftools-1.9/bcftools consensus -f 221021hap1_assembly.fa -H 1 hap1.out_phased.vcf.gz > hap1_phased_haplotype1.fasta
The site Chr1_1:4195225 overlaps with another variant, skipping...
The site Chr1_1:4201421 overlaps with another variant, skipping...
The site Chr1_1:4202106 overlaps with another variant, skipping...
The site Chr1_1:28824762 overlaps with another variant, skipping...
The site Chr1_1:30388601 overlaps with another variant, skipping...
The fasta sequence does not match the REF allele at Chr2_1:28577524:
   .vcf: [A]
   .vcf: [ATATTATTTTACTATGCAAATG] <- (ALT)
   .fa:  [G]TATTATTTGCAAACGTATAGCCGGGCGGCTATACTGTTTAAATGCGGCGGTACTATAACACTTTATAAACACACCCAAAACCCATCATTACACACACTCAAAACTCATTTATAAACACACCCAAAAAGTTGACTTTAGGGTTAATTTTGGGTGTGTTTCTATGTTTAAATAGTGCTTGGGTTTTTTTATAAATACATGTCTAGGATTGGGTTTATTTATAAATTTGTATTAAATCTATTCTTTTTAAACGTACAACCGCGCGGCTATAATATTTACAACGATGATAAAGGGTTTCTTTTTGTCATCATCCTCAGCCATGAGTTCTGTCATAGACACTCTATTTACTTAAGTTTACAATGTAAATAAGGAAGTATCCCCTATTTGGATTCAAATAAAAATGCTAGAAAATCAAATTCCCACCAAATCAAAATATAAAAAATCGGTTTTAGTGCAAAATACGATTTAGGCTAAAAATGATGGCTCATTAAGTCAATATATACTTTATACTAAAATTCCATAAAATCAAGTTTTCTTATTTGATGTGTAAAGAATAAAAGCCGCCAAAAATTATCTTGAGAAAATGATTATTTTGACAAACCATTTTTCATACTTAGTCAATATTTTTATATAAAATATTTTTTTCATGTATGATATGAATGCATGAAGGGACCTAAGGTTTTTTTTAGTTTGTGAAATTTTGATTTTTTTTCTTTCTATTGGGTTTAATAGGGGAAAAGGCTTTAAAGATATTTGCTAAATCGCTACTCTTTGTCTATCTCTTACAATTTTTCTTGCTTAAAATGTATTTGTCTATCTATTTGTCGAGGACAATTATGATTGCAACCAATAAGCAATAAATTCTTGACATATGTGATATATATATATATATACTATTTTTCGTATGTATTGTGAGTTCGAACTTTTGATTCTTTATAATTTATAAGAGGCCCCCACACACATGAAATCATGACTTCGCCATTGGTTCTGTTAATGGGGTTTTGTAAGATTCAGTTTA

**Comment by holtjma** [comment]
Going to close this for now, but if you find out this is an issue with HiPhase, we can re-open it.
