### ISSUE TITLE
Can I use the BAM from other technologies for phasing ?

### ISSUE THREAD

**Issue by charliechen912ilovbash** [PacificBiosciences/HiPhase#54]
For example:
`hiphase     --bam   hifi.bam   --bam nanopore.bam  --bam illumina.bam`

**Comment by holtjma** [comment]
Hi @charliechen912ilovbash,

We do not recommend (or support) using other technologies.  HiPhase expects certain length and quality of input data.  When those are reduced you're more likely to get errors in the outputs.

Matt
