### ISSUE TITLE
Phase polyloid variants

### ISSUE THREAD

**Issue by ywzhang071394** [PacificBiosciences/HiPhase#56]
Hi,

I am wondering if your team is planing to develop a function for phasing polyloid variants, because tumor samples ofen show whole genome duplication.

Thanks

**Comment by holtjma** [comment]
Hi @ywzhang071394,

Currently, we do not have any plans to support polyploid datasets.  Separate from that (but similar) would be support for oncology, which is also not currently planned.  Another user recently asked about this, so you may find some useful information in that issue: https://github.com/PacificBiosciences/HiPhase/issues/52 

Matt

**Comment by ywzhang071394** [comment]
sure thanks!
