### ISSUE TITLE
Feature request: CRAM compatible

### ISSUE THREAD

**Issue by Audald** [PacificBiosciences/HiPhase#6]
Thanks for developing `HiPhase`. Will it be possible to input CRAM files and output haplotagged CRAM files? That would suit perfectly our data architecture.

**Comment by holtjma** [comment]
We have not internally tested it yet, so I'm glad it works for you!

I'm pleasantly surprised it does, I'm going to re-open this to remind me to investigate if there are any subtle issues with CRAM.  For example, we are not passing the reference to the parsing interface which I assumed would lead to an error, but maybe it is inferring it from your CRAM file header.

**Comment by holtjma** [comment]
Yep, that was one thing I was worried about.  In the short-term, I think you may need to just use the bam to cram workaround.  We'll take a look at this in the coming weeks and hopefully get a patch in the next release.

**Comment by Audald** [comment]
Many thanks @holtjma!
